name: droplyric
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.3
  sqflite_common_ffi: ^2.4.2+1
  path_provider: ^2.1.6
  path: ^1.9.1
  http: ^1.6.0
  url_launcher: ^6.3.2
  sqflite_common_ffi_web: ^1.1.2
  just_audio: ^0.10.6
  app_links: ^6.3.2
  crypto: ^3.0.6
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.17
  youtube_explode_dart: ^2.2.1
  youtube_player_iframe: ^6.0.2

  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/spotify.svg
    - assets/logo.png
    - assets/splash_logo.png
    - assets/creator.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  macos:
    generate: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#000000"
  image: assets/splash_logo.png
  android_12:
    image: assets/splash_logo.png
    color: "#000000"
    icon_background_color: "#000000"
  ios: true
  android: true